/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#a3d1b6",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#00201f",
        "background": "#fef9f0",
        "tertiary-container": "#572c00",
        "secondary-container": "#9feee9",
        "outline": "#717973",
        "on-primary-fixed-variant": "#254f3a",
        "on-background": "#1d1c16",
        "secondary": "#0a6a67",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f5f0e7",
        "tertiary-fixed": "#ffdcc3",
        "tertiary-fixed-dim": "#ffb77d",
        "on-primary": "#ffffff",
        "tertiary": "#371a00",
        "primary-fixed": "#bfedd2",
        "on-tertiary-fixed": "#2f1500",
        "on-tertiary-fixed-variant": "#6e3900",
        "secondary-fixed": "#a2f0ec",
        "surface-variant": "#e7e2d9",
        "on-primary-container": "#7da990",
        "on-surface-variant": "#414943",
        "inverse-primary": "#a3d1b6",
        "secondary-fixed-dim": "#86d4d0",
        "error": "#ba1a1a",
        "surface-container-low": "#f8f3ea",
        "on-tertiary-container": "#ec861d",
        "surface-bright": "#fef9f0",
        "outline-variant": "#c1c8c1",
        "on-secondary": "#ffffff",
        "primary": "#002718",
        "primary-container": "#133e2b",
        "on-error": "#ffffff",
        "surface-container-highest": "#e7e2d9",
        "on-primary-fixed": "#002113",
        "on-secondary-fixed-variant": "#00504d",
        "surface-container": "#f2ede4",
        "on-secondary-container": "#146e6b",
        "inverse-surface": "#32302a",
        "surface-tint": "#3d6751",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#ede8df",
        "error-container": "#ffdad6",
        "on-surface": "#1d1c16",
        "surface": "#fef9f0",
        "surface-dim": "#ded9d1"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-md": "1rem",
        "gutter-desktop": "1.5rem",
        "container-padding-mobile": "1rem",
        "space-sm": "0.75rem",
        "space-xs": "0.5rem",
        "container-padding-desktop": "2.5rem",
        "voice-dock-height": "5.5rem",
        "space-3xl": "4rem",
        "gutter-mobile": "0.75rem",
        "space-lg": "1.5rem",
        "space-2xl": "3rem",
        "space-xl": "2rem",
        "container-padding-tablet": "1.5rem"
      },
      fontFamily: {
        "headline-sm": ["Plus Jakarta Sans"],
        "body-xl": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "display-hero": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "display-hero-mobile": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-xl": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-hero": ["44px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-hero-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-lg": ["15px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
};
